dist: bionic

addons:
  firefox: latest
  chrome: stable

services:
  - xvfb

language: node_js
node_js:
  - "12.16.1"
branches:
only:
  - master
before_script:

script:
  - npm install -g firebase-tools
  - npm run build 
  - firebase deploy --token $FIREBASE_TOKEN
  - npm test
after_success:
  
notifications:
  email: jordisabadell@gmail.com
  on_failure: always
  on_success: always